version: "3.1"

services:
  oracle_node_1:
    build:
      context: ./eyeOracle_for_all
      dockerfile: Dockerfile
    image: oracle_tester:v1
    env_file:
      - eyeOracle_for_all/.env
    volumes:
      - ./oracle_logs/worker.log:/app/worker.log # Monta un archivo en lugar de un directorio
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6479
    ports:
      - "4000:3000" # Exponer el puerto del servidor Express

  redis:
    image: redis:latest
    container_name: redis-oracle_tester
    ports:
      - "6479:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
    driver: local
