version: "3.1"

services:
  oracle_node_1:
    build:
      context: ./oracle_node
      dockerfile: Dockerfile
    image: oracle_node_1:v1

    env_file:
      - oracle_node/.env
  redis:
    image: redis:latest
    container_name: redis-oracle_node_1
    ports:
      - "6379:6379" # Mapea el puerto 6379 del contenedor al puerto 6379 del host
    volumes:
      - redis-data:/data # Opcional: persiste los datos de Redis en un volumen
    restart: always # Reinicia el contenedor automáticamente en caso de fallo

volumes:
  redis-data:
    driver: local
