version: "3.1"

services:
  oracle_node_1:
    build:
      context: ./oracle_node
      dockerfile: Dockerfile
    image: oracle_node_1:v1

    env_file:
      - oracle_node/.env
  redis:
    image: redis:latest
    container_name: redis-oracle_node_1
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
    driver: local
